### ISSUE TITLE
Apache Flink et Kafka Streams

### ISSUE THREAD

**Issue by arnaudbos** [monkeytechdays/cfp#1]
## A propos de vous

* Prénom Nom: Arnaud Bos & Guillaume Andrieu
* Email : arnaud at monkeypatch point io & guillaume at monkeypatch point io
* Téléphone : Même pas en rêve.
* Utilisateur Twitter : arnaud_bos & glmxndr

---

## Description de votre sujet.

Depuis 2011 et la sortie d’Apache Storm, les frameworks de “stream processing” ont révolutionné la capacité des entreprises modernes à extraire de la valeur de leurs flux de données. Les architectures ont évolué d’analyses basées sur des données historiques (batch), vers la fameuse architecture lambda pour maintenant s’orienter vers le “stream processing first”.
Dans ce domaine, Storm et le micro-batching de Spark tiennent le haut du pavé mais Flink apporte un modèle d’exécution et une architecture qui le font monter en popularité.
De son côté, Kafka a sû s’imposer comme un incontournable des architectures big data et propose depuis peu une librairie de “stream-processing”.
Pour ce MonkeyTechDay, nous proposons une journée d’exploration d’Apache Flink et Apache Kafka pendant laquelle nous évaluerons les APIs des deux outils et modéliserons un jeu collaboratif basé sur le traitements de différents flux d’évènements.

---

## Détails

* Avez-vous déjà une idée d’exercices/HandsOn/app pour assurer la comparaison des technos et leur prise en main : exercices pour appréhender les API le matin puis un jeu collaboratif l’après-midi
* Tags (e.g: angular, android, web, iot) : BIG
* Disponibilité (e.g: ASAP, avant/aprés XXX): le 16/03/2018 à 09:00 (UTC+1)

**Comment by ilaborie** [comment]
Done
