### ISSUE TITLE
Mobile Cross Platform - Kotlin vs Flutter

### ISSUE THREAD

**Issue by EmmanuelVinas** [monkeytechdays/cfp#3]
## A propos de vous

* Prénom Nom: Emmanuel V ou Alexandre Delattre (Kotlin)  et Kevin Segaud (Flutter)

---

## Description de votre sujet.

Depuis le début des smartphones, beaucoup de technologies cross platform ont émergé. 
Deux technologies nous nous semblent pertinentes en ce moment, dans l'optique de mutualiser les développements Mobiles sur différentes plateformes : Kotlin et Flutter

* Nom de la techno/langage/librairie : Kotlin & Flutter

* Format : TP le matin / Appli l'apres midi 

## Détails

* Tags (e.g: angular, android, web, iot) : Android, iOS, Flutter, Kotlin
* Disponibilité (e.g: ASAP, avant/aprés XXX): A partir de Juillet

**Comment by ilaborie** [comment]
Vous allez faire du Kotlin iOS ?
