### ISSUE TITLE
Functional JVM : Eta vs Scala

### ISSUE THREAD

**Issue by glmxndr** [monkeytechdays/cfp#5]
## A propos de vous

* Prénom Nom: Guillaume ANDRIEU
* Utilisateur Twitter : @glmxndr

---

## Description de votre sujet.

* Nom de la techno/langage/librairie : Eta (haskell sur la JVM) (https://eta-lang.org)
* Techno alternative : Scala (https://www.scala-lang.org/)

* Format : TP le matin / Refactor d'appli existante l'apres midi

---

## Détails

* Exos basés sur du refactor de code: une appli est donnée en Java, et on traduit des bouts dans le langage choisi, ce qui permet de tester l'interop avec Java en même temps que de découvrir le langage
* Tags : jvm, functional programming, eta, haskell, scala
* Disponibilité (e.g: ASAP, avant/aprés XXX): ?

**Comment by ilaborie** [comment]
Techniquement je veux bien faire le coach Scala, mais de l'autre coté je suis aussi tenté par faire les exos Eta

**Comment by EmmanuelVinas** [comment]
eta is dead
